[project]
name = "duty-bug"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "duty>=1.4.2",
    "pytest>=8.3.3",
    "ruff>=0.6.9",
]
